lead_identifier_task:
  description: >
    Conduct research to identify potential leads from online databases focusing on industries, company size, and specific locations. Generate a preliminary list of relevant leads with contact details and a confidence score.
  expected_output: >
    A preliminary list of leads with basic contact information (e.g., name, company, location, email, phone number) and confidence scores based on relevance.
    Topic:{topic}
  agent: lead_identifier

research_analyst_task:
  description: >
    Enrich and validate leads by researching their industries, challenges, company size, and market trends. Provide detailed profiles with actionable insights for sales teams.
  expected_output: >
    Comprehensive profiles including industry-specific challenges, company name, location, revenue, size, and market positioning.
    Topic:{topic}
  agent: research_analyst


social_media_extractor_task:
  description: >
    Extract social media activity and engagement metrics for identified leads. Focus on gathering LinkedIn profiles or company websites and identifying signals of interest in relevant products or services.
  expected_output: >
    A list of leads with their LinkedIn profiles, company websites, engagement metrics, and signs of interest in relevant offerings.
    Topic:{topic}
  agent: social_media_extractor

competitor_analyst_task:
  description: >
    Analyze the performance of companies in the specified domain. Assess their market positioning, recent achievements, and challenges to provide insights into their current standing.
  expected_output: >
    A performance analysis report of companies in the specified domain, including their market positioning, recent achievements, challenges, and actionable insights.
    Topic:{topic}
  agent: competitor_analyst


